version: "3.7"

services:
  php-localhost:
    container_name: php-localhost
    build:
      dockerfile: ./.docker/php/Dockerfile
      context: .
      args:
        USER_ID: $USER_ID
    env_file: .env
    volumes:
      - .:/var/www/html/:ro
    ports:
      - "8080:9000"